export { default as Loader } from './Loader'
export { default as Home } from './Home'
export { default as Navbar } from './NavBar'
export { default as Button } from './Button'
export { default as GeneralCard } from './GeneralCard'
